import Link from 'next/link'
import { notFound } from 'next/navigation'
import { SiteFooter } from '@/components/SiteFooter'
import { UnlockMoment } from '@/components/UnlockMoment'
import { achievementByUnlockToken } from '@/lib/db'

/**
 * The unlock. This is the product.
 *
 * It is rendered on the server and complete on first paint — the share card is
 * already generated by the time this page loads, because a spinner at the
 * moment of payoff destroys both the feeling and the measurement we are here
 * to take.
 */
export const dynamic = 'force-dynamic'

export const metadata = { robots: { index: false, follow: false } }

export default async function UnlockPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const achievement = await achievementByUnlockToken(token)
  if (!achievement) notFound()

  return (
    <>
      <UnlockMoment a={achievement} />
      <div className="mx-auto max-w-2xl px-6 pb-16">
        <Link href={`/a/${achievement.token}`} className="text-sm underline">
          View your public page
        </Link>
      </div>
      <SiteFooter />
    </>
  )
}
